# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker client
          command: |
            docker build . -t dotenet-docker
            echo 'bonjour'
      - deploy: 
          name: Push application Docker image
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag dotenet-docker silversnitch/dotenet-docker
            docker push silversnitch/dotenet-docker