# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-1604:202004-01"
    steps:
      - checkout
      - run:
          name: Build Docker client
          command: |
            docker build . -t dotenet-docker
            docker run -p 8080:8080 -d dotenet-docker
            sleep 2
            curl -I localhost:8080 | grep "200 OK"
  deploy: 
    machine:
      image: "ubuntu-1604:202004-01"
    steps: 
      - checkout
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag dotenet-docker silversnitch/dotenet-docker
            docker push silversnitch/dotenet-docker

workflows:
  executor:
    jobs:
      - build
      - publish:
          requires:
            - build